functionsDirectory = "/mnt/d/Projects area/Programming projects/Web base/mohssin-personal-site/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/mnt/d/Projects area/Programming projects/Web base/mohssin-personal-site/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/mnt/d/Projects area/Programming projects/Web base/mohssin-personal-site/netlify/functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]